"""Migration: None

Revision ID: 3f6f1a9e861a
Revises: 
Create Date: 2025-08-31 07:22:15

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6f1a9e861a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration."""
    # ### commands auto generated by Raystack ###
    op.execute('''CREATE TABLE IF NOT EXISTS groups_groupmodel ("id" TEXT PRIMARY KEY, "name" TEXT UNIQUE NOT NULL, "description" TEXT NOT NULL)''')
    op.execute('''CREATE TABLE IF NOT EXISTS users_usermodel ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "age" TEXT NOT NULL, "email" TEXT NOT NULL, "password_hash" TEXT NOT NULL, "group" TEXT NOT NULL, "organization" TEXT NOT NULL, "is_active" TEXT NOT NULL, "is_superuser" TEXT NOT NULL)''')
    # ### end Raystack commands ###


def downgrade():
    """Revert migration."""
    # ### commands auto generated by Raystack ###
    op.execute('DROP TABLE IF EXISTS groups_groupmodel')
    op.execute('DROP TABLE IF EXISTS users_usermodel')
    # ### end Raystack commands ###
